### ISSUE TITLE
Please update source code

### ISSUE THREAD

**Issue by l396** [MediaBrowser/Douban#4]
Hello.

I see that the version of the douban plugin in the Emby plugins catalog is 1.0.3, and the version here is 1.0.0.

Can you please update the source code here to the latest.

Since douban closes the public API, I would like to use another way to get douban data.

Thank you.

**Comment by LukePulverenti** [comment]
It is the latest: https://github.com/MediaBrowser/Douban/blob/master/Douban/Douban.csproj#L5

**Comment by l396** [comment]
Sorry, didn't look closely at the source code before. This is the latest version.
